-- Initialize PostgreSQL databases for WSO2 Identity Server
-- This script is automatically run when PostgreSQL container starts

-- Create WSO2 Identity database
CREATE DATABASE wso2is_identity WITH ENCODING 'UTF8';

-- Create WSO2 Shared database
CREATE DATABASE wso2is_shared WITH ENCODING 'UTF8';

-- Create WSO2 API Manager database
CREATE DATABASE wso2apim_shared WITH ENCODING 'UTF8';

-- Connect to wso2is_identity to create required tables
\c wso2is_identity

-- Create core WSO2IS schema tables for user management and identity
CREATE TABLE IF NOT EXISTS um_domain (
    UM_DOMAIN_ID SERIAL NOT NULL,
    UM_DOMAIN_NAME VARCHAR(255) NOT NULL UNIQUE,
    UM_CREATED_DATE BIGINT,
    PRIMARY KEY (UM_DOMAIN_ID)
);

CREATE TABLE IF NOT EXISTS um_tenant (
    UM_ID SERIAL NOT NULL,
    UM_DOMAIN_NAME VARCHAR(255) NOT NULL,
    UM_CREATED_DATE BIGINT,
    UM_EMAIL VARCHAR(255),
    UM_ACTIVE BOOLEAN,
    PRIMARY KEY (UM_ID),
    FOREIGN KEY (UM_DOMAIN_NAME) REFERENCES um_domain(UM_DOMAIN_NAME)
);

CREATE TABLE IF NOT EXISTS um_user (
    UM_ID INTEGER NOT NULL,
    UM_USER_ID VARCHAR(255) NOT NULL,
    UM_USER_NAME VARCHAR(255) NOT NULL,
    UM_DOMAIN_ID INTEGER,
    UM_TENANT_ID INTEGER,
    PRIMARY KEY (UM_ID),
    UNIQUE (UM_USER_NAME, UM_TENANT_ID)
);

CREATE TABLE IF NOT EXISTS um_user_password (
    UM_ID SERIAL NOT NULL,
    UM_USER_ID VARCHAR(255) NOT NULL,
    UM_PASSWORD VARCHAR(255),
    UM_SALT_VALUE VARCHAR(31),
    UM_REQUIRE_CHANGE BOOLEAN,
    UM_CHANGED_TIME BIGINT,
    UM_TENANT_ID INTEGER,
    PRIMARY KEY (UM_ID),
    UNIQUE (UM_USER_ID, UM_TENANT_ID)
);

CREATE TABLE IF NOT EXISTS um_role (
    UM_ID SERIAL NOT NULL,
    UM_ROLE_ID VARCHAR(255) NOT NULL,
    UM_ROLE_NAME VARCHAR(255) NOT NULL,
    UM_TENANT_ID INTEGER,
    PRIMARY KEY (UM_ID),
    UNIQUE (UM_ROLE_NAME, UM_TENANT_ID)
);

CREATE TABLE IF NOT EXISTS um_user_role (
    UM_ID SERIAL NOT NULL,
    UM_USER_ID VARCHAR(255),
    UM_ROLE_ID VARCHAR(255),
    UM_TENANT_ID INTEGER,
    PRIMARY KEY (UM_ID)
);

CREATE TABLE IF NOT EXISTS um_permission (
    UM_ID SERIAL NOT NULL,
    UM_RESOURCE_ID VARCHAR(255) NOT NULL,
    UM_ACTION VARCHAR(255) NOT NULL,
    UM_TENANT_ID INTEGER,
    PRIMARY KEY (UM_ID),
    UNIQUE (UM_RESOURCE_ID, UM_ACTION, UM_TENANT_ID)
);

CREATE TABLE IF NOT EXISTS um_role_permission (
    UM_ID SERIAL NOT NULL,
    UM_PERMISSION_ID INTEGER,
    UM_ROLE_ID VARCHAR(255),
    UM_TENANT_ID INTEGER,
    PRIMARY KEY (UM_ID)
);

CREATE TABLE IF NOT EXISTS um_user_attribute (
    UM_ID SERIAL NOT NULL,
    UM_USER_ID VARCHAR(255),
    UM_ATTR_NAME VARCHAR(255),
    UM_ATTR_VALUE TEXT,
    UM_PROFILE_ID VARCHAR(255),
    UM_TENANT_ID INTEGER,
    PRIMARY KEY (UM_ID)
);

-- Connect to wso2is_shared to create required shared tables
\c wso2is_shared

CREATE TABLE IF NOT EXISTS shared_user (
    UM_ID SERIAL NOT NULL,
    UM_USER_ID VARCHAR(255) NOT NULL,
    UM_USER_NAME VARCHAR(255) NOT NULL,
    UM_TENANT_ID INTEGER,
    PRIMARY KEY (UM_ID)
);
