-- WSO2 IS 7.1.0 consent-management (CM_*) tables.
--
-- Found missing during the H2 -> PostgreSQL migration rehearsal
-- (doc/WSO2_PROD_MIGRATION_PLAN.md): these 10 tables exist in WSO2IS 7.1.0's
-- auto-provisioned H2 identity schema but have no equivalent in
-- dartserver-config/environments/*/wso2is-config/postgresql-identity.sql,
-- which predates this WSO2IS version. DDL below is translated from the live
-- H2 schema (org.h2.tools.Script ... -options nodata against a fresh
-- WSO2IS 7.1.0 instance), following the same style as the existing
-- postgresql-identity.sql (VARCHAR, NEXTVAL sequences, unquoted uppercase
-- identifiers).
--
-- MUST be merged into postgresql-identity.sql (append, after the existing
-- CREATE TABLE statements but before any trailing ALTER TABLE / FK block)
-- before this migration tooling is run against real production data -
-- otherwise consent-receipt rows are silently dropped.

CREATE SEQUENCE IF NOT EXISTS CM_PII_CATEGORY_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_PII_CATEGORY (
            ID INTEGER DEFAULT NEXTVAL('CM_PII_CATEGORY_PK_SEQ'),
            NAME VARCHAR(255) NOT NULL,
            DESCRIPTION VARCHAR(1023),
            DISPLAY_NAME VARCHAR(255),
            IS_SENSITIVE INTEGER NOT NULL,
            TENANT_ID INTEGER DEFAULT -1234,
            PRIMARY KEY (ID),
            UNIQUE (NAME, TENANT_ID)
);

CREATE TABLE IF NOT EXISTS CM_RECEIPT (
            CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
            VERSION VARCHAR(255) NOT NULL,
            JURISDICTION VARCHAR(255) NOT NULL,
            CONSENT_TIMESTAMP TIMESTAMP NOT NULL,
            COLLECTION_METHOD VARCHAR(255) NOT NULL,
            LANGUAGE VARCHAR(255) NOT NULL,
            PII_PRINCIPAL_ID VARCHAR(255) NOT NULL,
            PRINCIPAL_TENANT_ID INTEGER DEFAULT -1234,
            POLICY_URL VARCHAR(255) NOT NULL,
            STATE VARCHAR(255) NOT NULL,
            PII_CONTROLLER VARCHAR(2048) NOT NULL,
            PRIMARY KEY (CONSENT_RECEIPT_ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_PURPOSE_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_PURPOSE (
            ID INTEGER DEFAULT NEXTVAL('CM_PURPOSE_PK_SEQ'),
            NAME VARCHAR(255) NOT NULL,
            DESCRIPTION VARCHAR(1023),
            PURPOSE_GROUP VARCHAR(255) NOT NULL,
            GROUP_TYPE VARCHAR(255) NOT NULL,
            TENANT_ID INTEGER DEFAULT -1234,
            PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_PURPOSE_CATEGORY_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_PURPOSE_CATEGORY (
            ID INTEGER DEFAULT NEXTVAL('CM_PURPOSE_CATEGORY_PK_SEQ'),
            NAME VARCHAR(255) NOT NULL,
            DESCRIPTION VARCHAR(1023),
            TENANT_ID INTEGER DEFAULT -1234,
            PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_RECEIPT_SP_ASSOC_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_RECEIPT_SP_ASSOC (
            ID INTEGER DEFAULT NEXTVAL('CM_RECEIPT_SP_ASSOC_PK_SEQ'),
            CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
            SP_NAME VARCHAR(255) NOT NULL,
            SP_DISPLAY_NAME VARCHAR(255),
            SP_DESCRIPTION VARCHAR(1024),
            SP_TENANT_ID INTEGER DEFAULT -1234,
            PRIMARY KEY (ID),
            UNIQUE (CONSENT_RECEIPT_ID, SP_NAME, SP_TENANT_ID),
            FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES CM_RECEIPT(CONSENT_RECEIPT_ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_SP_PURPOSE_ASSOC_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_SP_PURPOSE_ASSOC (
            ID INTEGER DEFAULT NEXTVAL('CM_SP_PURPOSE_ASSOC_PK_SEQ'),
            RECEIPT_SP_ASSOC INTEGER NOT NULL,
            PURPOSE_ID INTEGER NOT NULL,
            CONSENT_TYPE VARCHAR(255) NOT NULL,
            IS_PRIMARY_PURPOSE INTEGER NOT NULL,
            TERMINATION VARCHAR(255) NOT NULL,
            THIRD_PARTY_DISCLOSURE INTEGER NOT NULL,
            THIRD_PARTY_NAME VARCHAR(255),
            PRIMARY KEY (ID),
            FOREIGN KEY (RECEIPT_SP_ASSOC) REFERENCES CM_RECEIPT_SP_ASSOC(ID),
            FOREIGN KEY (PURPOSE_ID) REFERENCES CM_PURPOSE(ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_SP_PURPOSE_PURPOSE_CAT_ASSC_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_SP_PURPOSE_PURPOSE_CAT_ASSC (
            ID INTEGER DEFAULT NEXTVAL('CM_SP_PURPOSE_PURPOSE_CAT_ASSC_PK_SEQ'),
            SP_PURPOSE_ASSOC_ID INTEGER NOT NULL,
            PURPOSE_CATEGORY_ID INTEGER NOT NULL,
            PRIMARY KEY (ID),
            FOREIGN KEY (SP_PURPOSE_ASSOC_ID) REFERENCES CM_SP_PURPOSE_ASSOC(ID),
            FOREIGN KEY (PURPOSE_CATEGORY_ID) REFERENCES CM_PURPOSE_CATEGORY(ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_PURPOSE_PII_CAT_ASSOC_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_PURPOSE_PII_CAT_ASSOC (
            ID INTEGER DEFAULT NEXTVAL('CM_PURPOSE_PII_CAT_ASSOC_PK_SEQ'),
            PURPOSE_ID INTEGER NOT NULL,
            CM_PII_CATEGORY_ID INTEGER NOT NULL,
            IS_MANDATORY INTEGER NOT NULL,
            PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_SP_PURPOSE_PII_CAT_ASSOC_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_SP_PURPOSE_PII_CAT_ASSOC (
            ID INTEGER DEFAULT NEXTVAL('CM_SP_PURPOSE_PII_CAT_ASSOC_PK_SEQ'),
            SP_PURPOSE_ASSOC_ID INTEGER NOT NULL,
            PII_CATEGORY_ID INTEGER NOT NULL,
            VALIDITY VARCHAR(1023),
            IS_CONSENTED BOOLEAN DEFAULT TRUE,
            PRIMARY KEY (ID),
            UNIQUE (SP_PURPOSE_ASSOC_ID, PII_CATEGORY_ID),
            FOREIGN KEY (SP_PURPOSE_ASSOC_ID) REFERENCES CM_SP_PURPOSE_ASSOC(ID),
            FOREIGN KEY (PII_CATEGORY_ID) REFERENCES CM_PII_CATEGORY(ID)
);

CREATE SEQUENCE IF NOT EXISTS CM_CONSENT_RECEIPT_PROPERTY_PK_SEQ;
CREATE TABLE IF NOT EXISTS CM_CONSENT_RECEIPT_PROPERTY (
            ID INTEGER DEFAULT NEXTVAL('CM_CONSENT_RECEIPT_PROPERTY_PK_SEQ'),
            CONSENT_RECEIPT_ID VARCHAR(255) NOT NULL,
            NAME VARCHAR(255) NOT NULL,
            VALUE VARCHAR(1023) NOT NULL,
            PRIMARY KEY (ID),
            UNIQUE (CONSENT_RECEIPT_ID, NAME),
            FOREIGN KEY (CONSENT_RECEIPT_ID) REFERENCES CM_RECEIPT(CONSENT_RECEIPT_ID)
);
