"""Initial migration - create player, gametype, gameresults, and scores tables

Revision ID: 95f33c1ce707
Revises:
Create Date: 2025-10-07 21:40:27.667730

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95f33c1ce707"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gametype",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gameresults",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_type_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("player_order", sa.Integer(), nullable=False),
        sa.Column("start_score", sa.Integer(), nullable=True),
        sa.Column("final_score", sa.Integer(), nullable=True),
        sa.Column("is_winner", sa.Boolean(), nullable=True),
        sa.Column("double_out_enabled", sa.Boolean(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("game_session_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["game_type_id"], ["gametype.id"]),
        sa.ForeignKeyConstraint(["player_id"], ["player.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_result_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("throw_sequence", sa.Integer(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("throw_in_turn", sa.Integer(), nullable=False),
        sa.Column("base_score", sa.Integer(), nullable=False),
        sa.Column("multiplier", sa.String(length=20), nullable=False),
        sa.Column("multiplier_value", sa.Integer(), nullable=False),
        sa.Column("actual_score", sa.Integer(), nullable=False),
        sa.Column("score_before", sa.Integer(), nullable=False),
        sa.Column("score_after", sa.Integer(), nullable=False),
        sa.Column("dartboard_sends_actual_score", sa.Boolean(), nullable=False),
        sa.Column("is_bust", sa.Boolean(), nullable=True),
        sa.Column("is_finish", sa.Boolean(), nullable=True),
        sa.Column("thrown_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["game_result_id"], ["gameresults.id"]),
        sa.ForeignKeyConstraint(["player_id"], ["player.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scores")
    op.drop_table("gameresults")
    op.drop_table("player")
    op.drop_table("gametype")
    # ### end Alembic commands ###
