[server]
hostname = "localhost"
node_ip = "127.0.0.1"

[transport.https.properties]
proxyPort = 443

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[database.apim_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2AM_DB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE"
username = "wso2carbon"
password = "wso2carbon"

[database.shared_db]
type = "h2"
url = "jdbc:h2:./repository/database/WSO2SHARED_DB;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE"
username = "wso2carbon"
password = "wso2carbon"

[apim.idp]
server_url = "https://wso2is:9443"

[apim.key_manager]
service_url = "https://wso2is:9443"

[keymanager.default]
serverUrl = "https://wso2is:9443"
introspectionUrl = "https://wso2is:9443/oauth2/introspect"
tokenUrl = "https://wso2is:9443/oauth2/token"
revokeUrl = "https://wso2is:9443/oauth2/revoke"
scopeManagementUrl = "https://wso2is:9443/api/identity/oauth2/v1.0/scopes"
userInfoUrl = "https://wso2is:9443/oauth2/userinfo"
authorizeUrl = "https://wso2is:9443/oauth2/authorize"
jwksUrl = "https://wso2is:9443/oauth2/jwks"
certificateAlias = "wso2carbon"
clientRegistrationEndpoint = "https://wso2is:9443/api/identity/oauth2/dcr/v1.1/register"
issuer = "https://wso2is:9443"
username = "nPf0KSQo1fLd0Moe871xhxbnRmMa"
password = "bf8SBCMANAK5Lhi6UtgOUKPSvx_fiFPdMUmYOm30iVoa"

[[keymanager.default.grant_types]]
displayName = "Code"
value = "authorization_code"

[[keymanager.default.grant_types]]
displayName = "Implicit"
value = "implicit"

[[keymanager.default.grant_types]]
displayName = "Password"
value = "password"

[[keymanager.default.grant_types]]
displayName = "Client Credentials"
value = "client_credentials"

[[keymanager.default.grant_types]]
displayName = "Refresh Token"
value = "refresh_token"

[[keymanager.default.grant_types]]
displayName = "JWT Bearer"
value = "urn:ietf:params:oauth:grant-type:jwt-bearer"

[[keymanager.default.certificate_type]]
name = "JWKS"
enabled = true

[[keymanager.default.certificate_type]]
name = "PEM"
enabled = true

[oauth2.oidc]
client_id = "y3yrE1W8yohQWGl3cDdyOfySV_sa"
client_secret = "wOi3Lnql72EDVGb9dwo2brxQj3EkspGZvSj0bAyfKH4a"
server_url = "https://localhost:5000"
authorize_endpoint = "https://localhost:5000/oauth2/authorize"
token_endpoint = "https://localhost:5000/oauth2/token"
revoke_endpoint = "https://localhost:5000/oauth2/revoke"
userinfo_endpoint = "https://localhost:5000/oauth2/userinfo"
oidc_logout_endpoint = "https://localhost:5000/oidc/logout"
oidc_session_iframe_endpoint = "https://localhost:5000/oidc/checksession"
scope = "openid profile email"
